In [3]:
import numpy as np

In [4]:
distance = [55,60,45]
speed=[6, 10, 7]
dist=np.array(distance)
spd=np.array(speed)
time = dist/spd
print(time)

[9.16666667 6.         6.42857143]


In [7]:
# data type
print("data type of array: ", time.dtype)

# number of dimensions
print("number of dimensions: ", time.ndim)

#Size of each dimension
print("size of each dimension: ", time.shape)

#Total size of the array
print("total size of the array: ", time.size)

data type of array:  float64
number of dimensions:  1
size of each dimension:  (3,)
total size of the array:  3


In [10]:
# Creating arrays with random values
np.random.seed(0) # set seed for reproducibility

x1 = np.random.randint(10, size=6) #A one dimensional array
x2 = np.random.randint(10, size=(3, 4)) #A Tow dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #A three dimensional array

print('x1 ndim', x1.ndim)
print('x1 shape', x1.shape)
print('x1 size', x1.size)

print('x2 ndim', x2.ndim)
print('x2 shape', x2.shape)
print('x2 size', x2.size)

print('x3 ndim', x3.ndim)
print('x3 shape', x3.shape)
print('x3 size', x3.size)

x1 ndim 1
x1 shape (6,)
x1 size 6
x2 ndim 2
x2 shape (3, 4)
x2 size 12
x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [12]:
f = np.arange(0, 20, 5)
print("Sequential array with steps of 5: \n", f)

Sequential array with steps of 5: 
 [ 0  5 10 15]


In [14]:
print("1-d array:", x1)
print("Second element of the first array:", x1[1])
print("last element of the first array:", x1[-1])
print("first element of the first array:", x1[0])

1-d array: [5 0 3 3 7 9]
Second element of the first array: 0
last element of the first array: 9
first element of the first array: 5


In [15]:
print("2-d array: \n", x2)
print("first elements in a 2-D array: \n", x2[0, 0])
print("3-d array: \n", x3)
print("The first element in a 3-D array: \n", x3[0, 0, 0])

2-d array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
first elements in a 2-D array: 
 3
3-d array: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
The first element in a 3-D array: 
 8


In [16]:
# Create an array
x=np.arange(10)
print('Our array: ', x)
print('The first five elements of the array', x[:5])
print('The last five elements of the array', x[-5:])
print('Elements after index 5:', x[5:])
print('Middle sub-array:', x[4:7])
print('Every other element:', x[::2])
print('Every other element starting from index 1', x[1::2])
print('Elements in reversed order:', x[::-1])

Our array:  [0 1 2 3 4 5 6 7 8 9]
The first five elements of the array [0 1 2 3 4]
The last five elements of the array [5 6 7 8 9]
Elements after index 5: [5 6 7 8 9]
Middle sub-array: [4 5 6]
Every other element: [0 2 4 6 8]
Every other element starting from index 1 [1 3 5 7 9]
Elements in reversed order: [9 8 7 6 5 4 3 2 1 0]
