In [1]:
import numpy as np

In [2]:
distance = [55,60,45]
speed=[6, 10, 7]
dist=np.array(distance)
spd=np.array(speed)
time = dist/spd
print(time)

[9.16666667 6.         6.42857143]


In [3]:
# data type
print("data type of array: ", time.dtype)

# number of dimensions
print("number of dimensions: ", time.ndim)

#Size of each dimension
print("size of each dimension: ", time.shape)

#Total size of the array
print("total size of the array: ", time.size)

data type of array:  float64
number of dimensions:  1
size of each dimension:  (3,)
total size of the array:  3


In [4]:
# Creating arrays with random values
np.random.seed(0) # set seed for reproducibility

x1 = np.random.randint(10, size=6) #A one dimensional array
x2 = np.random.randint(10, size=(3, 4)) #A Tow dimensional array
x3 = np.random.randint(10, size=(3,4,5)) #A three dimensional array

print('x1 ndim', x1.ndim)
print('x1 shape', x1.shape)
print('x1 size', x1.size)

print('x2 ndim', x2.ndim)
print('x2 shape', x2.shape)
print('x2 size', x2.size)

print('x3 ndim', x3.ndim)
print('x3 shape', x3.shape)
print('x3 size', x3.size)

x1 ndim 1
x1 shape (6,)
x1 size 6
x2 ndim 2
x2 shape (3, 4)
x2 size 12
x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [5]:
f = np.arange(0, 20, 5)
print("Sequential array with steps of 5: \n", f)

Sequential array with steps of 5: 
 [ 0  5 10 15]


In [6]:
print("1-d array:", x1)
print("Second element of the first array:", x1[1])
print("last element of the first array:", x1[-1])
print("first element of the first array:", x1[0])

1-d array: [5 0 3 3 7 9]
Second element of the first array: 0
last element of the first array: 9
first element of the first array: 5


In [7]:
print("2-d array: \n", x2)
print("first elements in a 2-D array: \n", x2[0, 0])
print("3-d array: \n", x3)
print("The first element in a 3-D array: \n", x3[0, 0, 0])

2-d array: 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
first elements in a 2-D array: 
 3
3-d array: 
 [[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
The first element in a 3-D array: 
 8


In [8]:
# Create an array
x=np.arange(10)
print('Our array: ', x)
print('The first five elements of the array', x[:5])
print('The last five elements of the array', x[-5:])
print('Elements after index 5:', x[5:])
print('Middle sub-array:', x[4:7])
print('Every other element:', x[::2])
print('Every other element starting from index 1', x[1::2])
print('Elements in reversed order:', x[::-1])

Our array:  [0 1 2 3 4 5 6 7 8 9]
The first five elements of the array [0 1 2 3 4]
The last five elements of the array [5 6 7 8 9]
Elements after index 5: [5 6 7 8 9]
Middle sub-array: [4 5 6]
Every other element: [0 2 4 6 8]
Every other element starting from index 1 [1 3 5 7 9]
Elements in reversed order: [9 8 7 6 5 4 3 2 1 0]


In [9]:
# Creating two sample arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

# Combining both arrays using concatenate
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [10]:
# Creating a sample array
x = np.array([1, 2, 3])

grid = np.array([[1, 2, 3], [4, 5, 6]])

# np.vstack([x, grid])

y = np.array([[99], [99]])

np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [11]:
import pandas as pd

In [12]:
# Creating an empty series
x = pd.Series()
print("An empty series example: ", x)

An empty series example:  Series([], dtype: object)


In [13]:
# Series example
import pandas as pd
series1 = pd.Series([1, 2, 3, 4, 5])
print(series1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [14]:
series2 = pd.Series([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(series2)

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64


In [15]:
# Reindexing the default index column
series3 = pd.Series([10, 20, 30, 50], index=['a', 'b', 'c', 'd'])
print(series3)

a    10
b    20
c    30
d    50
dtype: int64


In [16]:
series3['d']

50

In [17]:
# Data manipulation in a series
print('Adding 5 to a series: \n', series3 + 5)
print('Filtering series with greater than 30 \n', series3[series3 > 30])
print('Square root of a series elements: \n', np.sqrt(series3))

Adding 5 to a series: 
 a    15
b    25
c    35
d    55
dtype: int64
Filtering series with greater than 30 
 d    50
dtype: int64
Square root of a series elements: 
 a    3.162278
b    4.472136
c    5.477226
d    7.071068
dtype: float64


In [18]:
# Converting a dictionary to a series
data = {'abc': 1, 'def': 2, 'ghi': 3}
print('Dictionary example: \n', data)

pd.Series(data)

Dictionary example: 
 {'abc': 1, 'def': 2, 'ghi': 3}


abc    1
def    2
ghi    3
dtype: int64

In [19]:
# Creating an empty dataframe
df = pd.DataFrame()
print('Data Frame example: \n', df)

Data Frame example: 
 Empty DataFrame
Columns: []
Index: []


In [20]:
# A sample list containing name and age
data = [
    ['Tom', 10],
    ['Harry', 12],
    ['Jim', 13]
]

# Creating a dataframe from a given list
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0    Tom   10
1  Harry   12
2    Jim   13

In [21]:
# df['Name']
df.Name

0      Tom
1    Harry
2      Jim
Name: Name, dtype: object

In [22]:
# Adding a column to an existing dataframe
df['Year'] = 2008
df

Name  Age  Year
0    Tom   10  2008
1  Harry   12  2008
2    Jim   13  2008

In [23]:
del df['Year']
df

Name  Age
0    Tom   10
1  Harry   12
2    Jim   13

In [24]:
df.pop('Age')
df

Name
0    Tom
1  Harry
2    Jim

In [25]:
# A sample dataframe containing the company stock price
data = pd.DataFrame(
    {
        'price': [95, 25, 85, 41], 
        'ticker': ['AXP', 'CSCO', 'DIS', 'MSFT'], 
        'company': ['American Express', 'Cisco Systems', 'Disney', 'Microsoft']
        }
)

data

price ticker           company
0     95    AXP  American Express
1     25   CSCO     Cisco Systems
2     85    DIS            Disney
3     41   MSFT         Microsoft

In [26]:
# Access the value that is at index 0, in column 'company' using loc
print(data.loc[0]['company'])

# Access the value that is at index 0, in column 'company' using iloc
print(data.iloc[0]['company'])

American Express
American Express


In [27]:
# Inspecting the top 5 rows of a dataframe
print('Top five data: \n', data.head())

# Inspecting the bottom 5 rows of a dataframe
print('The bottom 5 data points: \n', data.tail())

Top five data: 
    price ticker           company
0     95    AXP  American Express
1     25   CSCO     Cisco Systems
2     85    DIS            Disney
3     41   MSFT         Microsoft
The bottom 5 data points: 
    price ticker           company
0     95    AXP  American Express
1     25   CSCO     Cisco Systems
2     85    DIS            Disney
3     41   MSFT         Microsoft


In [28]:
# Checking the  datatype of a column
data.dtypes

price       int64
ticker     object
company    object
dtype: object

In [29]:
data.describe()

price
count   4.000000
mean   61.500000
std    33.798422
min    25.000000
25%    37.000000
50%    63.000000
75%    87.500000
max    95.000000

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   price    4 non-null      int64 
 1   ticker   4 non-null      object
 2   company  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [31]:
# A simple dataframe
import numpy as np
df = pd.DataFrame(np.random.randn(5, 3), index=['a', 'c', 'e', 'f', 'h'], columns=['one', 'two', 'three'])

# Creating data with missing values by reindexing
df2 = df.reindex(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
df2

one       two     three
a  1.254414  1.419102 -0.743856
b       NaN       NaN       NaN
c -2.517437 -1.507096  1.149076
d       NaN       NaN       NaN
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
g       NaN       NaN       NaN
h -0.375666 -0.038224  0.367974

In [32]:
# Checking the missing values using isNull()
print(df2.isnull())
missing_values_count = df2.isnull().sum()
print('Count of missing values: \n', missing_values_count)

     one    two  three
a  False  False  False
b   True   True   True
c  False  False  False
d   True   True   True
e  False  False  False
f  False  False  False
g   True   True   True
h  False  False  False
Count of missing values: 
 one      3
two      3
three    3
dtype: int64


In [33]:
# Remove all columns with at least one missing value
columns_with_na_dropped = df2.dropna(axis=1)
columns_with_na_dropped.head()

Empty DataFrame
Columns: []
Index: [a, b, c, d, e]

In [34]:
# Filling NaN with zeros
df3 = df2.fillna(0)
df3

one       two     three
a  1.254414  1.419102 -0.743856
b  0.000000  0.000000  0.000000
c -2.517437 -1.507096  1.149076
d  0.000000  0.000000  0.000000
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
g  0.000000  0.000000  0.000000
h -0.375666 -0.038224  0.367974

In [35]:
# Replace all NA's the value that comes directly after it in the same column
# then replace all the remaining na's with 0
df4 = df2.fillna(method='bfill', axis=0).fillna(0)
df4

one       two     three
a  1.254414  1.419102 -0.743856
b -2.517437 -1.507096  1.149076
c -2.517437 -1.507096  1.149076
d -1.193578  1.141042  1.509445
e -1.193578  1.141042  1.509445
f  1.067775 -0.686589  0.014873
g -0.375666 -0.038224  0.367974
h -0.375666 -0.038224  0.367974

In [36]:
import sqlalchemy as db

In [37]:
# The database connection logic
import os
from dotenv import find_dotenv, load_dotenv
from sqlalchemy import create_engine

ENV = load_dotenv(find_dotenv())

MYSQL_USERNAME = os.environ.get("MYSQL_USER")
MYSQL_PASSWORD = os.environ.get("MYSQL_PASSWORD")
MYSQL_DATABASE = os.environ.get("MYSQL_DATABASE")

DB_URL = f"mysql+pymysql://{MYSQL_USERNAME}:{MYSQL_PASSWORD}@localhost/datascience_intro"

engine = create_engine(DB_URL)

connection = engine.connect()

In [38]:
query = "CREATE TABLE customers (name VARCHAR(255), address VARCHAR(255))"

In [39]:
connection.execute(query)
print('Table Name: ', engine.table_names())
connection.close()

ObjectNotExecutableError: Not an executable object: 'CREATE TABLE customers (name VARCHAR(255), address VARCHAR(255))'

<p>Some SQL insert statements for the database</p>

In [ ]:
engine = db.create_engine(f'mysql+pymysql://{MYSQL_USERNAME}:{MYSQL_PASSWORD}@localhost/datascience_intro')
connection = engine.connect()
sql = "INSERT INTO customers (name, address) VALUES ('ChickenWings', 'Are Us')"
connection.execute(sql)
connection.close()

ObjectNotExecutableError: Not an executable object: "INSERT INTO customers (name, address) VALUES ('ChickenWings', 'Are Us')"

In [ ]:
engine = db.create_engine(f'mysql+pymysql://{MYSQL_USERNAME}:{MYSQL_PASSWORD}@localhost:3306/datascience_intro')
connection = engine.connect()
sql = 'SELECT * FROM customers'
result = connection.execute(sql)
print('table data: ', result.fetchall())
connection.close()

ObjectNotExecutableError: Not an executable object: 'SELECT * FROM customers'

In [ ]:
engine = db.create_engine(f'mysql+pymysql://{MYSQL_DATABASE}:{MYSQL_PASSWORD}@localhost:3306/datascience_intro')
connection = engine.connect()
sql = 'UPDATE customers SET address = "Canyon 123" WHERE address = "Valley 345"'
connection.execute(sql)
print('Record(s) have been updated')
q = 'SELECT * FROM customers'
result = connection.execute(q)
print('table data: ', result.fetchall())
connection.close()

RuntimeError: 'cryptography' package is required for sha256_password or caching_sha2_password auth methods

In [40]:
engine = db.create_engine(f'mysql+pymysql://{MYSQL_USERNAME}:{MYSQL_PASSWORD}@localhost:3306/datascience_intro')
connection = engine.connect()
sql = 'DELETE FROM customers WHERE address = "Singapore"'
connection.execute(sql)
print("Record has been deleted")
connection.close()

ObjectNotExecutableError: Not an executable object: 'DELETE FROM customers WHERE address = "Singapore"'

<p>Inner join</p>

In [42]:
query = 'CREATE TABLE IF NOT EXISTS users (id INT, name VARCHAR(255), prod_id INT)'
connection.execute(query)
sql='INSERT INTO users (id, name, prod_id) VALUES (1, "John", 11), (2, "Peter", 22), (3, "Susan", 33), (4, "Helen", 44), (5, "Mark", 55)'
connection.execute(sql)
query2='CREATE TABLE IF NOT EXISTS products (id INT, name VARCHAR(255))'
connection.execute(query2)
sql2 = 'INSERT INTO products (id, name) VALUES (11, "Bread"), (22, "Milk"), (33, "Cheese"), (44, "Butter"), (55, "Salt")'
connection.execute(sql2)
connection.commit()
connection.close()

ObjectNotExecutableError: Not an executable object: 'CREATE TABLE IF NOT EXISTS users (id INT, name VARCHAR(255), prod_id INT)'

<h1>Statistics and stuff</h1>

In [46]:
import pandas as pd
import numpy as np

a = np.array([[1,2], [3, 4]])
print(np.mean(a))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

df = pd.DataFrame(a)

2.5
[2. 3.]
[1.5 3.5]


In [47]:
# Some median code
a=np.array([[10, 7, 4], [3,2,1]])
print(np.median(a))

3.5
